```{r}
library(tidyverse)
library(ggplot2)
library(wesanderson)
library(RColorBrewer )
```


```{r}
#params
title_size=40
text_size= 30
axis_size= 8
strip_size= 8
```


```{r}
#data
data <- read.csv("../results/bea/all_parent/all_parent_2dig.csv")
glimpse(data)
```

```{r}
# TG
data %>%
  ggplot(aes(year, TGasset, color = sector)) +
  geom_line(size = 1, alpha = 0.6)+
  # facet_wrap(~sector)+ #scales = "free"
  scale_y_continuous(labels = scales::percent)+
  theme_minimal()+
  labs(title= "Tasa de ganancia (sin rotación) de inversiones de EEUU", subtitle = "All parent companies")+
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        legend.text = element_text(size = axis_size),
        axis.text.x = element_text(angle = 45, size= axis_size),
        axis.text.y = element_text(size= axis_size),
        axis.title  = element_blank(),
        
        )#+
  # scale_color_manual(values=wes_palette(n=length(unique(data$sector)), name="Royal2"))
ggsave("../results/bea/all_parent/tg_asset_all_parent.png")

```

